# Generated by Django 2.0.6 on 2018-07-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
